
import json
import xml.etree.ElementTree as ET
import boto3
import botocore


BUCKET_NAME = "bucketgare"
s3 = boto3.resource('s3')

def lambda_handler(event, context):
    try:
        classifica = {}
        
        ##
        ### Recupero Headers
        ##
        
        # id della gara, corrispondente al nome del file xml nel bucket
        race_id_param = event["queryStringParameters"]["id"] 
        # categoria di cui voglio la  classifica
        categoria_param = event["queryStringParameters"]["class"]
        
        race_id_param = race_id_param + ".xml"
        
        
        ##
        ### Recupero File XML 
        ##

        # Creo oggetto bucket prendendo il file indicato nella header
        s3obj = s3.Object(BUCKET_NAME, race_id_param)
        
        # Leggo string dell' xml dal bucket
        xmlstring = s3obj.get()['Body'].read().decode('ISO-8859-1')
        
        # Genero albero xml
        xml = ET.fromstring(xmlstring)
        
        
        ##
        ### Recupero elementi della cateogoria desiderata
        ##
        
        _ns = {
            "":'http://www.orienteering.org/datastandard/3.0'
        }
        
        # Id
        ids = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Person/Id", _ns)
       
        # Nome
        names = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Person/Name/Family", _ns)
        
        # Cognome
        surnames = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Person/Name/Given", _ns)
        
        # Time  Behind
        timeBehind = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Result/TimeBehind", _ns)
       
        # Time
        time = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Result/Time", _ns)
      
        #Score
        score = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Result/Score", _ns)
        
        #Status
        status = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Result/Status", _ns)
        
        #Club name 
        club = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Organisation/Name", _ns)
        
        #Country
        country = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Organisation/Country", _ns)
        
        #bib number
        bib = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Result/BibNumber", _ns)
        
        indexSconosciuto = 1 
      
        for x in range(len(ids)):
            
            
            idcorrect         = ids[x].text        if  len(ids)       > x else ""
            if idcorrect is None:
                 idcorrect         = "Id sconosciuto" + str(indexSconosciuto)
                 indexSconosciuto += 1
                
            namecorrect       = names[x].text      if len(names)      > x else ""
            surnamecorrect    = surnames[x].text   if len(surnames)   > x else ""
            timebehindcorrect = timeBehind[x].text if len(timeBehind) > x else ""
            timecorrect       = time[x].text       if len(time)       > x else ""
            scorecorrect      = score[x].text      if len(score)      > x else ""
            statuscorrect     = status[x].text     if len(status)     > x else ""
            clubcorrect       = club[x].text       if len(club)       > x else ""
            countrycorrect    = country[x].text    if len(country)    > x else ""
            bibcorrect        = bib[x].text        if len(bib)        > x else ""
            
            # In alcuni xml, timebehind non è disponibile, quindi controllo se ce l'ho a disposizione.
            if len(timeBehind) < len(ids):
                classifica[idcorrect]= {
                    "position": x+1,
                    "id": idcorrect,
                    "name" : namecorrect+" "+ surnamecorrect,
                    "score": scorecorrect,
                    "status": statuscorrect,
                    "club_name": clubcorrect,
                    "bib": bibcorrect,
                    "country": countrycorrect,
                    "nat": "",
                    "time": timecorrect,
                    "score": scorecorrect
                }
                
            else:
                classifica[idcorrect]=  {
                    "position": x+1,
                    "id": idcorrect,
                    "name" : namecorrect+" "+ surnamecorrect,
                    "status": statuscorrect,
                    "club_name": clubcorrect,
                    "bib": bibcorrect,
                    "country": countrycorrect,
                    "nat": "",
                    "time": timecorrect, 
                    "score": scorecorrect

                }

        return {
            'statusCode': 200,
            'body': json.dumps(classifica)
        }
        
        
    except s3.meta.client.exceptions.NoSuchKey:    
        return {
            'statusCode': 404,
            'body': json.dumps("Nessun parametro trovato")
        }
        
    except Exception as e:
        print(e)
        return {
            'statusCode': 404,
            'body': json.dumps(str(e))
        }
        import json
        import xml.etree.ElementTree as ET
        import boto3
        import botocore


        BUCKET_NAME = "bucketgare"
        s3 = boto3.resource('s3')

        def lambda_handler(event, context):
                try:
                            classifica = {}
                                    
                                            ##
                                                    ### Recupero Headers
                                                            ##
                                                                    
                                                                            # id della gara, corrispondente al nome del file xml nel bucket
                                                                                    race_id_param = event["queryStringParameters"]["id"] 
                                                                                            # categoria di cui voglio la  classifica
                                                                                                    categoria_param = event["queryStringParameters"]["class"]
                                                                                                            
                                                                                                                    race_id_param = race_id_param + ".xml"
                                                                                                                            
                                                                                                                                    
                                                                                                                                            ##
                                                                                                                                                    ### Recupero File XML 
                                                                                                                                                            ##

                                                                                                                                                                    # Creo oggetto bucket prendendo il file indicato nella header
                                                                                                                                                                            s3obj = s3.Object(BUCKET_NAME, race_id_param)
                                                                                                                                                                                    
                                                                                                                                                                                            # Leggo string dell' xml dal bucket
                                                                                                                                                                                                    xmlstring = s3obj.get()['Body'].read().decode('ISO-8859-1')
                                                                                                                                                                                                            
                                                                                                                                                                                                                    # Genero albero xml
                                                                                                                                                                                                                            xml = ET.fromstring(xmlstring)
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                    ##
                                                                                                                                                                                                                                                            ### Recupero elementi della cateogoria desiderata
                                                                                                                                                                                                                                                                    ##
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                    _ns = {
                                                                                                                                                                                                                                                                                                        "":'http://www.orienteering.org/datastandard/3.0'
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            # Id
                                                                                                                                                                                                                                                                                                    ids = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Person/Id", _ns)
                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                   # Nome
                                                                                                                                                                                                                                                                                                                           names = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Person/Name/Family", _ns)
                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                           # Cognome
                                                                                                                                                                                                                                                                                                                                                   surnames = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Person/Name/Given", _ns)
                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                   # Time  Behind
                                                                                                                                                                                                                                                                                                                                                                           timeBehind = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Result/TimeBehind", _ns)
                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                          # Time
                                                                                                                                                                                                                                                                                                                                                                                                  time = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Result/Time", _ns)
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                #Score
                                                                                                                                                                                                                                                                                                                                                                                                                        score = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Result/Score", _ns)
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                        #Status
                                                                                                                                                                                                                                                                                                                                                                                                                                                status = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Result/Status", _ns)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                #Club name 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        club = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Organisation/Name", _ns)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        #Country
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                country = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Organisation/Country", _ns)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                #bib number
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bib = xml.findall("./ClassResult/Class[Name ='" + categoria_param +  "']/../PersonResult/Result/BibNumber", _ns)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        indexSconosciuto = 1 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for x in range(len(ids)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      idcorrect         = ids[x].text        if  len(ids)       > x else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if idcorrect is None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       idcorrect         = "Id sconosciuto" + str(indexSconosciuto)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        indexSconosciuto += 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    namecorrect       = names[x].text      if len(names)      > x else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                surnamecorrect    = surnames[x].text   if len(surnames)   > x else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            timebehindcorrect = timeBehind[x].text if len(timeBehind) > x else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        timecorrect       = time[x].text       if len(time)       > x else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scorecorrect      = score[x].text      if len(score)      > x else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                statuscorrect     = status[x].text     if len(status)     > x else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            clubcorrect       = club[x].text       if len(club)       > x else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        countrycorrect    = country[x].text    if len(country)    > x else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bibcorrect        = bib[x].text        if len(bib)        > x else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # In alcuni xml, timebehind non è disponibile, quindi controllo se ce l'ho a disposizione.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if len(timeBehind) < len(ids):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            classifica[idcorrect]= {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "position": x+1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "id": idcorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "name" : namecorrect+" "+ surnamecorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "score": scorecorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "status": statuscorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "club_name": clubcorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "bib": bibcorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "country": countrycorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "nat": "",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "time": timecorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "score": scorecorrect
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            classifica[idcorrect]=  {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "position": x+1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "id": idcorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "name" : namecorrect+" "+ surnamecorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "status": statuscorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "club_name": clubcorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "bib": bibcorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "country": countrycorrect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "nat": "",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "time": timecorrect, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "score": scorecorrect

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'statusCode': 200,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'body': json.dumps(classifica)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except s3.meta.client.exceptions.NoSuchKey:    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'statusCode': 404,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'body': json.dumps("Nessun parametro trovato")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(e)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'statusCode': 404,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'body': json.dumps(str(e))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
